# -*- coding: utf-8 -*-
"""Detectot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1If_BCDv2pUQLWoZd2A_Od2yppUU9lvo1
"""

!pip install scikit-learn pandas numpy --quiet
!pip install joblib

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import NMF
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import joblib

DATA = pd.read_csv('decphi_dataset.csv', on_bad_lines='skip')
df = pd.DataFrame(DATA)
df= pd.DataFrame(DATA).dropna()

X_train, X_test, y_train, y_test = train_test_split(df["Phishing Data"], df["Phishing Class"], test_size=0.3, random_state=42)

model = Pipeline([
    ('tfidf', TfidfVectorizer(stop_words='english', ngram_range=(1,2))),  # capture patterns and URLs
    ('nmf', NMF(n_components=50, random_state=42)),
    ('knn', KNeighborsClassifier(n_neighbors=5))
])

model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))

joblib.dump(model,"decphi.pkl")

from google.colab import files
files.download("decphi.pkl")